version: "3.7"
services: 
    redis: 
        image: redis
        container_name: redis_database
        restart: unless-stopped
        ports : 
            - 6379:6379
        networks: 
            - app-network
    application:
        build: 
            context: ./
            dockerfile: Dockerfile
        container_name: application
        restart: unless-stopped
        ports : 
            - 8080:8080
        depends_on : 
            - redis
        environment :
            - REDIS_SERVER=redis
            - REDIS_PORT=6379
        networks: 
            - app-network
    prometheus:
        image: prom/prometheus:latest
        container_name: monitoring_prometheus
        restart: unless-stopped
        volumes:
            - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml:ro
        expose:
            - 9090
        ports:
            - 9090:9090
        networks: 
            - app-network
    grafana:
        image: grafana/grafana:latest
        container_name: monitoring_grafana
        restart: unless-stopped
        links:
            - prometheus:prometheus
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
            - GF_USERS_ALLOW_SIGN_UP=false
            - GF_SERVER_DOMAIN=myrul.com
            - GF_SMTP_ENABLED=false
            - GF_SMTP_HOST=smtp.gmail.com:587
        networks: 
            - app-network
networks:
    app-network: 
        